language: node_js
sudo: false

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'

cache:
  directories:
    - node_modules

after_script:
  - npm run lint
  - mkdir -p coverage
  - npm run coverage
  - npm run publish-coverage
